name: Build WPF App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true

    - name: Upload published app
      uses: actions/upload-artifact@v3
      with:
        name: WPFApp
        path: '**/bin/Release/net6.0-windows/win-x64/publish/'
